Starting.........
User(id=978944103, is_self=False, contact=True, mutual_contact=False, deleted=False, bot=False, bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False, attach_menu_enabled=False, bot_can_edit=False, close_friend=False, stories_hidden=False, stories_unavailable=True, contact_require_premium=False, bot_business=False, bot_has_main_app=False, access_hash=-9050570891987208542, first_name='unknown', last_name=None, username=None, phone='972544470875', photo=None, status=UserStatusOffline(was_online=datetime.datetime(2024, 12, 8, 15, 10, 14, tzinfo=datetime.timezone.utc)), bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[], stories_max_id=None, color=None, profile_color=None, bot_active_users=None)
User added successfully.
User added successfully.
User added successfully.
User added successfully.
User added successfully.
Error adding user: list index out of range
Error adding user: list index out of range
User added successfully.
User added successfully.
User added successfully.
Error adding user: list index out of range
User added successfully.
User added successfully.
User added successfully.
User added successfully.
User added successfully.
Error adding user: list index out of range
Error adding user: A wait of 69 seconds is required (caused by ImportContactsRequest)
Extracted seconds: 69
Error adding user: list index out of range
User added successfully.
User added successfully.
User added successfully.
Error adding user: list index out of range
User added successfully.
Error adding user: list index out of range
Error adding user: list index out of range
User added successfully.
Error adding user: list index out of range
User added successfully.
Error adding user: list index out of range
Error adding user: list index out of range
Error adding user: list index out of range
Error adding user: list index out of range
Error adding user: list index out of range
Error adding user: list index out of range
Error adding user: list index out of range
Error adding user: list index out of range
Error adding user: list index out of range
Error adding user: list index out of range
Error adding user: list index out of range
Traceback (most recent call last):
  File "/workspaces/my-chats/main.py", line 139, in <module>
    client.loop.run_until_complete(create_and_add_user())
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 671, in run_until_complete
    self.run_forever()
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 638, in run_forever
    self._run_once()
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 1971, in _run_once
    handle._run()
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/workspaces/my-chats/main.py", line 38, in create_and_add_user
    time.sleep(50)
KeyboardInterrupt
